// Keywords to search for that could imply a special/deal
export const KEYWORDS = [
  'deal',
  '%',
  'discount',
  'special',
  'offer',
  'promotion',
  'sale',
  'limited time',
  'exclusive',
  'coupon',
  'voucher',
  'save',
  'BOGO',
  'free',
  'half price',
  '50%',
  'anniversary',
  'grand opening',
] as const;

// Regex patterns that could match a date range
// ordered by precedence
export const DATE_PATTERNS = [
  /from (.*?) to (.*?)/i,
  /between (.*?) and (.*?)/i,
  /(\w+ \d{1,2})(?:st|nd|rd|th)? to (\w+ \d{1,2})/i,
  /until (.*?)/i,
  /till (.*?)/i,
  /through (.*?)/i,
  /on (\w+ \d{1,2})/i,
  /(\w+ \d{1,2})(?:st|nd|rd|th)?/i,
  /(\w+day)/i,
] as const;

export const INSTAGRAM_USERNAMES = [
  'marcelloeats',
  'torontofood.guide',
  'halalornothing',
  'munchhalal',
  'oneworldhalalfoodie',
  'ttceats',
  'torontohalal',
  'halal_to',
  'banbanchk.ca',
  'banbanchk.scarborough',
  'krispykremecan',
  'shelbyscanada',
  'chickenndough',
  'krispyfry_chicken',
  'simbashotchicken',
  'burnsroadkarachi',
  'tahinisrestaurants',
  'sumaqbbq',
  'aleppokebab.ca',
  'pizzakarachi',
  'wingspotmarkham',
  'dspotcafe',
] as const;
