// List of Instagram usernames to scrape for deals
export const INSTAGRAM_SOURCES = [
  'marcelloeats',
  'torontofood.guide',
  'halalornothing',
  'munchhalal',
  'oneworldhalalfoodie',
  'ttceats',
  'torontohalal',
  'halal_to',
  'banbanchk.ca',
  'banbanchk.scarborough',
  'krispykremecan',
  'shelbyscanada',
  'chickenndough',
  'chickqueenmarkham',
  'chickqueencanada',
  'krispyfry_chicken',
  'simbashotchicken',
  'burnsroadkarachi',
  'tahinisrestaurants',
  'sumaqbbq',
  'aleppokebab.ca',
  'pizzakarachi',
  'wingspotmarkham',
  'dspotcafe',
] as const;
